@extends('layouts.app')
@section('content')
@if($slides->isNotEmpty())
<section class="home-slider"><div id="homeCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel"><div class="carousel-indicators">@foreach($slides as $slide)<button type="button" data-bs-target="#homeCarousel" data-bs-slide-to="{{ $loop->index }}" class="{{ $loop->first?'active':'' }}" aria-label="Слайд {{ $loop->iteration }}"></button>@endforeach</div><div class="carousel-inner">@foreach($slides as $slide)<div class="carousel-item {{ $loop->first?'active':'' }}"><img src="{{ Storage::url($slide->image_path) }}" class="d-block w-100" alt="{{ $slide->title }}"><div class="carousel-overlay"></div><div class="carousel-caption container"><div class="eyebrow"><i class="bi bi-water"></i> {{ $site['site_name'] }}</div><h1>{{ $slide->title }}</h1><p>{{ $slide->subtitle }}</p>@if($slide->button_text)<a href="{{ $slide->button_url ?: route('booking.index') }}" class="btn btn-primary btn-lg rounded-pill px-4">{{ $slide->button_text }} <i class="bi bi-arrow-right ms-2"></i></a>@endif</div></div>@endforeach</div><button class="carousel-control-prev" type="button" data-bs-target="#homeCarousel" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span></button><button class="carousel-control-next" type="button" data-bs-target="#homeCarousel" data-bs-slide="next"><span class="carousel-control-next-icon"></span></button></div></section>
@else
<section class="hero-section"><div class="container position-relative"><div class="row align-items-center g-5 min-vh-75"><div class="col-lg-7 py-5"><div class="eyebrow"><i class="bi bi-water"></i> {{ $site['city'] }} · Зеленодольский район</div><h1>Ваше море рядом.<br><span>Бассейн и SPA</span> для всей семьи</h1><p class="hero-lead">25-метровый бассейн с морской водой температурой 32°C, профессиональные тренеры и пространство для восстановления.</p><div class="d-flex flex-column flex-sm-row gap-3 mt-4"><a href="{{ route('booking.index') }}" class="btn btn-primary btn-lg rounded-pill px-4">Подобрать время</a><a href="{{ route('catalog.index') }}" class="btn btn-outline-light btn-lg rounded-pill px-4">Купить абонемент</a></div></div><div class="col-lg-5"><div class="hero-card"><span class="hero-card-icon"><i class="bi bi-calendar2-check"></i></span><h3>Найдём удобное время</h3><p>Выберите услугу, дату и доступный слот онлайн.</p><a href="{{ route('booking.index') }}" class="btn btn-light w-100 rounded-pill py-3 fw-bold">Посмотреть расписание</a></div></div></div></div></section>
@endif

<section class="section-padding intro-section"><div class="container"><div class="row g-4 align-items-end mb-5"><div class="col-lg-7"><div class="eyebrow eyebrow-blue">Комплекс заботы о себе</div><h2 class="section-title">Движение, отдых и восстановление <span>в одном месте</span></h2></div><div class="col-lg-5"><p class="section-text mb-0">Приходите всей семьёй: научиться плавать, поддерживать форму, расслабиться или пройти курс SPA-процедур.</p></div></div><div class="row g-4"><div class="col-md-4"><div class="feature-card"><span><i class="bi bi-droplet"></i></span><h4>Морская вода</h4><p>Комфортная температура 32°C и мягкая атмосфера для занятий и отдыха.</p></div></div><div class="col-md-4"><div class="feature-card"><span><i class="bi bi-person-arms-up"></i></span><h4>Тренеры рядом</h4><p>Обучение плаванию взрослых и детей, индивидуальные и групповые занятия.</p></div></div><div class="col-md-4"><div class="feature-card"><span><i class="bi bi-flower1"></i></span><h4>SPA-восстановление</h4><p>Массаж, прессотерапия, душ Шарко, сауна и соляная комната.</p></div></div></div></div></section>

<section class="section-padding services-section" id="services"><div class="container"><div class="text-center mx-auto section-heading"><div class="eyebrow eyebrow-blue justify-content-center">Выберите свой формат</div><h2 class="section-title">Услуги комплекса</h2></div><div class="row g-4 mt-3">@php($icons=['pool'=>'bi-water','training'=>'bi-stopwatch','spa'=>'bi-flower2','salt'=>'bi-cloud-haze2']) @forelse($services as $service)<div class="col-md-6 col-xl-4"><div class="service-card h-100"><div class="service-icon"><i class="bi {{ $icons[$service->category]??'bi-stars' }}"></i></div><div class="service-meta"><span>{{ $service->duration_minutes }} мин</span><span>до {{ $service->capacity }} чел.</span></div><h3>{{ $service->name }}</h3><p>{{ $service->description }}</p><div class="d-flex justify-content-between align-items-center mt-auto pt-3"><strong class="service-price">от {{ number_format($service->price,0,',',' ') }} ₽</strong><a href="{{ route('booking.index',['service'=>$service->id]) }}" class="circle-link"><i class="bi bi-arrow-up-right"></i></a></div></div></div>@empty<div class="col-12"><div class="alert alert-light">Выполните <code>php artisan db:seed</code>, чтобы заполнить услуги.</div></div>@endforelse</div></div></section>

@if($trainers->isNotEmpty())<section class="section-padding trainers-section"><div class="container"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-5"><div><div class="eyebrow eyebrow-blue">Профессиональная команда</div><h2 class="section-title mb-0">Наши тренеры</h2></div><a href="{{ route('booking.index') }}" class="btn btn-outline-primary rounded-pill px-4">Записаться к тренеру</a></div><div class="row g-4">@foreach($trainers as $trainer)<div class="col-md-6 col-xl-4"><div class="trainer-card">@if($trainer->photo_path)<img src="{{ Storage::url($trainer->photo_path) }}" alt="{{ $trainer->name }}">@else<div class="trainer-placeholder"><i class="bi bi-person"></i></div>@endif<div class="trainer-card-body"><small>{{ $trainer->specialization }}</small><h3>{{ $trainer->name }}</h3><p>{{ Str::limit($trainer->bio,150) }}</p>@if($trainer->experience_years)<span><i class="bi bi-award"></i> Стаж {{ $trainer->experience_years }} лет</span>@endif</div></div></div>@endforeach</div></div></section>@endif

@if($latestNews->isNotEmpty())<section class="section-padding home-news"><div class="container"><div class="d-flex justify-content-between align-items-end mb-5"><div><div class="eyebrow eyebrow-blue">Будьте в курсе</div><h2 class="section-title mb-0">Новости комплекса</h2></div><a href="{{ route('news.index') }}" class="btn btn-outline-primary rounded-pill">Все новости</a></div><div class="row g-4">@foreach($latestNews as $post)<div class="col-md-6 col-xl-4"><article class="content-card h-100">@if($post->image_path)<a href="{{ route('news.show',$post) }}"><img src="{{ Storage::url($post->image_path) }}" alt="{{ $post->title }}"></a>@endif<div class="content-card-body"><small>{{ optional($post->published_at)->translatedFormat('d F Y') }}</small><h2><a href="{{ route('news.show',$post) }}">{{ $post->title }}</a></h2><p>{{ $post->excerpt }}</p><a class="text-link" href="{{ route('news.show',$post) }}">Читать <i class="bi bi-arrow-right"></i></a></div></article></div>@endforeach</div></div></section>@endif

@if($galleryAlbums->isNotEmpty())<section class="section-padding home-gallery"><div class="container"><div class="d-flex justify-content-between align-items-end mb-5"><div><div class="eyebrow eyebrow-blue">Посмотрите своими глазами</div><h2 class="section-title mb-0">Фотогалерея</h2></div><a href="{{ route('gallery.index') }}" class="btn btn-outline-primary rounded-pill">Все альбомы</a></div><div class="home-gallery-grid">@foreach($galleryAlbums as $album)@php($cover=$album->cover_path?:optional($album->photos->first())->image_path) @if($cover)<a href="{{ route('gallery.show',$album) }}"><img src="{{ Storage::url($cover) }}" alt="{{ $album->title }}"><span>{{ $album->title }}</span></a>@endif @endforeach</div></div></section>@endif

@if($products->isNotEmpty())<section class="section-padding products-preview"><div class="container"><div class="d-flex justify-content-between align-items-end mb-5"><div><div class="eyebrow eyebrow-blue">Посещения и подарки</div><h2 class="section-title mb-0">Билеты, абонементы и сертификаты</h2></div><a href="{{ route('catalog.index') }}" class="btn btn-outline-primary rounded-pill px-4">Смотреть все</a></div><div class="row g-4">@foreach($products as $product)<div class="col-md-4"><div class="ticket-card h-100"><span class="ticket-type">{{ $product->type==='subscription'?'Абонемент':($product->type==='gift'?'Сертификат':'Билет') }}</span><h3>{{ $product->name }}</h3><p>{{ $product->description }}</p><div class="ticket-bottom"><strong>{{ number_format($product->price,0,',',' ') }} ₽</strong><a href="{{ route('catalog.index') }}" class="circle-link"><i class="bi bi-arrow-right"></i></a></div></div></div>@endforeach</div></div></section>@endif

<section class="gift-section"><div class="container"><div class="gift-card"><div class="gift-decoration">Γ</div><div class="row align-items-center g-4 position-relative"><div class="col-lg-8"><div class="eyebrow">Подарок новым подписчикам</div><h2>Напишите слово <span>«БАССЕЙН»</span></h2><p>Подпишитесь на <strong>{{ $site['social_handle'] }}</strong> и получите сеанс соляной комнаты в подарок.</p></div><div class="col-lg-4 text-lg-end"><a href="#callback" class="btn btn-light btn-lg rounded-pill px-4">Узнать подробнее</a></div></div></div></div></section>

<section class="section-padding callback-section" id="callback"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><div class="eyebrow eyebrow-blue">Нужна помощь?</div><h2 class="section-title">Подберём формат и удобное время</h2><p class="section-text">Оставьте номер телефона. Администратор поможет выбрать плавание, тренировку или процедуру.</p><div class="contact-pill"><i class="bi bi-telephone"></i><div><small>Позвонить сейчас</small><a href="tel:{{ preg_replace('/[^\d+]/','',$site['phone']) }}">{{ $site['phone'] }}</a></div></div></div><div class="col-lg-7"><div class="callback-card">@if(session('lead_success'))<div class="alert alert-success rounded-4">{{ session('lead_success') }}</div>@endif<form method="post" action="{{ route('lead.store') }}" class="row g-3">@csrf<div class="col-md-6"><label class="form-label">Ваше имя</label><input class="form-control form-control-lg" name="name" value="{{ old('name') }}" required></div><div class="col-md-6"><label class="form-label">Телефон</label><input class="form-control form-control-lg" name="phone" value="{{ old('phone') }}" required></div><div class="col-12"><label class="form-label">Что вас интересует?</label><textarea class="form-control" name="request" rows="3"></textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="privacy" value="1" id="privacyLead" required><label class="form-check-label small text-muted" for="privacyLead">Согласен с <a href="{{ route('privacy') }}">политикой обработки данных</a></label></div></div><div class="col-12"><button class="btn btn-primary btn-lg rounded-pill px-5">Перезвоните мне</button></div></form></div></div></div></div></section>

<section class="contact-section"><div class="container"><div class="contact-panel"><div class="row g-4 align-items-center"><div class="col-lg-7"><span class="contact-icon"><i class="bi bi-geo-alt"></i></span><div><small>Ждём вас по адресу</small><h3>{{ $site['address_full'] }}</h3><p class="mb-0">{{ $site['working_hours_weekdays'] }} · {{ $site['working_hours_weekends'] }}</p></div></div><div class="col-lg-5 text-lg-end"><a href="{{ $site['map_url'] ?: 'https://yandex.ru/maps/?text='.urlencode($site['address_full']) }}" target="_blank" rel="noopener" class="btn btn-outline-light btn-lg rounded-pill px-4">Открыть на карте <i class="bi bi-box-arrow-up-right ms-2"></i></a></div></div></div></div></section>
@endsection
