@extends('admin.layout')
@section('title','Аудит') @section('heading','Журнал действий') @section('eyebrow','Кто, что и когда изменил')
@section('content')
<div class="admin-card p-4">
<form class="row g-2 mb-4"><div class="col-md-3"><select class="form-select" name="user_id"><option value="">Все сотрудники</option>@foreach($users as $u)<option value="{{ $u->id }}" @selected(request('user_id')==$u->id)>{{ $u->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="action"><option value="">Все действия</option>@foreach($actions as $a)<option value="{{ $a }}" @selected(request('action')===$a)>{{ $a }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" name="route" value="{{ request('route') }}" placeholder="Маршрут"></div><div class="col-md-2"><input type="date" class="form-control" name="date_from" value="{{ request('date_from') }}"></div><div class="col-md-2"><input type="date" class="form-control" name="date_to" value="{{ request('date_to') }}"></div><div class="col-md-1"><button class="btn btn-primary w-100"><i class="bi bi-search"></i></button></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Время</th><th>Сотрудник</th><th>Действие</th><th>Объект</th><th>Маршрут</th><th>Изменения</th></tr></thead><tbody>
@forelse($logs as $log)<tr><td class="text-nowrap">{{ $log->created_at?->format('d.m.Y H:i:s') }}</td><td><strong>{{ $log->user?->name??'Система' }}</strong><small class="d-block text-muted">{{ $log->user?->role }}</small></td><td><span class="badge text-bg-light border">{{ $log->action }}</span></td><td><small>{{ class_basename($log->subject_type??'') }} @if($log->subject_id)#{{ $log->subject_id }}@endif</small></td><td><code>{{ $log->route_name }}</code><small class="d-block">{{ $log->method }} · {{ $log->ip_address }}</small></td><td><details><summary>Показать</summary><div class="small mt-2"><strong>До:</strong><pre class="bg-light p-2 rounded">{{ json_encode($log->before,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><strong>После:</strong><pre class="bg-light p-2 rounded">{{ json_encode($log->after,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><strong>Ввод:</strong><pre class="bg-light p-2 rounded">{{ json_encode(data_get($log->metadata,'input'),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></div></details></td></tr>
@empty<tr><td colspan="6" class="text-center text-muted py-5">Журнал пока пуст.</td></tr>@endforelse
</tbody></table></div>{{ $logs->links() }}
</div>
@endsection
