<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','CRM') — {{ $site['site_short_name'] }}</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="{{ asset('css/admin.css') }}" rel="stylesheet"><link href="{{ asset('css/admin-extensions.css') }}" rel="stylesheet"><link href="{{ asset('css/admin-pool.css') }}" rel="stylesheet">@stack('styles')</head><body>
@php($u=auth()->user()) @php($brandRoute=$u->role==='director'?'admin.director.dashboard':($u->role==='accountant'?'admin.finance.index':'admin.dashboard'))
<div class="admin-shell"><aside class="admin-sidebar"><a class="admin-brand" href="{{ route($brandRoute) }}"><span>Γ</span><div><strong>{{ $site['site_short_name'] }}</strong><small>{{ $u->roleLabel() }}</small></div></a><nav>
@if($u->hasPermission('dashboard.view'))<a class="{{ request()->routeIs('admin.dashboard')?'active':'' }}" href="{{ route('admin.dashboard') }}"><i class="bi bi-grid"></i>Обзор</a>@endif
@if($u->hasPermission('director.dashboard'))<a class="{{ request()->routeIs('admin.director.*')?'active':'' }}" href="{{ route('admin.director.dashboard') }}"><i class="bi bi-speedometer2"></i>Панель директора</a>@endif
@if($u->hasPermission('reception.workspace'))<a href="{{ route('reception.index') }}"><i class="bi bi-person-workspace"></i>Ресепшен</a>@endif
@if($u->hasPermission('coach.workspace'))<a href="{{ route('coach.index') }}"><i class="bi bi-stopwatch"></i>Рабочее место тренера</a>@endif

@if($u->hasPermission('pool.view')||$u->hasPermission('access.view')||$u->hasPermission('bookings.view')||$u->hasPermission('operations.view')||$u->hasPermission('medical.view'))<div class="nav-caption">Бассейн и проход</div>@endif
@if($u->hasPermission('pool.view'))<a class="{{ request()->routeIs('admin.pool.*')?'active':'' }}" href="{{ route('admin.pool.index') }}"><i class="bi bi-water"></i>Бассейн и дорожки</a>@endif
@if($u->hasPermission('access.view'))<a class="{{ request()->routeIs('admin.access.*')?'active':'' }}" href="{{ route('admin.access.index') }}"><i class="bi bi-qr-code-scan"></i>СКУД и проход</a>@endif
@if($u->hasPermission('medical.view'))<a class="{{ request()->routeIs('admin.medical.*')?'active':'' }}" href="{{ route('admin.medical.index') }}"><i class="bi bi-heart-pulse"></i>Медицинский модуль</a>@endif
@if($u->hasPermission('operations.view'))<a class="{{ request()->routeIs('admin.operations.*')?'active':'' }}" href="{{ route('admin.operations.index') }}"><i class="bi bi-activity"></i>Эксплуатация</a>@endif
@if($u->hasPermission('incidents.view'))<a class="{{ request()->routeIs('admin.incidents.*')?'active':'' }}" href="{{ route('admin.incidents.index') }}"><i class="bi bi-shield-exclamation"></i>Инциденты</a>@endif
@if($u->hasPermission('bookings.view'))<a class="{{ request()->routeIs('admin.schedule.*')?'active':'' }}" href="{{ route('admin.schedule.index') }}"><i class="bi bi-clock"></i>Расписание</a><a class="{{ request()->routeIs('admin.bookings.*')?'active':'' }}" href="{{ route('admin.bookings.index') }}"><i class="bi bi-calendar2-check"></i>Записи</a>@endif

@if($u->hasPermission('customers.view')||$u->hasPermission('memberships.view')||$u->hasPermission('families.view')||$u->hasPermission('swim_school.view')||$u->hasPermission('leads.view'))<div class="nav-caption">Клиенты и продажи</div>@endif
@if($u->hasPermission('customers.view'))<a class="{{ request()->routeIs('admin.customers.*')?'active':'' }}" href="{{ route('admin.customers.index') }}"><i class="bi bi-people"></i>Клиенты 360°</a>@endif
@if($u->hasPermission('families.view'))<a class="{{ request()->routeIs('admin.families.*')?'active':'' }}" href="{{ route('admin.families.index') }}"><i class="bi bi-people-fill"></i>Семьи</a>@endif
@if($u->hasPermission('swim_school.view'))<a class="{{ request()->routeIs('admin.swim-school.*')?'active':'' }}" href="{{ route('admin.swim-school.index') }}"><i class="bi bi-person-arms-up"></i>Школа плавания</a>@endif
@if($u->hasPermission('memberships.view'))<a class="{{ request()->routeIs('admin.memberships.*')?'active':'' }}" href="{{ route('admin.memberships.index') }}"><i class="bi bi-person-vcard"></i>Членства и пакеты</a>@endif
@if($u->hasPermission('pricing.manage'))<a class="{{ request()->routeIs('admin.pricing.*')?'active':'' }}" href="{{ route('admin.pricing.index') }}"><i class="bi bi-tags"></i>Динамические цены</a>@endif
@if($u->hasPermission('leads.view'))<a class="{{ request()->routeIs('admin.leads.*')?'active':'' }}" href="{{ route('admin.leads.index') }}"><i class="bi bi-funnel"></i>Лиды</a>@endif
@if($u->hasPermission('crm_plus.view'))<a class="{{ request()->routeIs('admin.crm-plus.*')?'active':'' }}" href="{{ route('admin.crm-plus.index') }}"><i class="bi bi-kanban"></i>CRM+</a>@endif
@if($u->hasPermission('orders.view'))<a class="{{ request()->routeIs('admin.orders.*')?'active':'' }}" href="{{ route('admin.orders.index') }}"><i class="bi bi-receipt"></i>Заказы</a>@endif
@if($u->hasPermission('certificates.view'))<a class="{{ request()->routeIs('admin.certificates.*')?'active':'' }}" href="{{ route('admin.certificates.index') }}"><i class="bi bi-gift"></i>Сертификаты</a>@endif

@if($u->hasPermission('cash.view')||$u->hasPermission('inventory.view')||$u->hasPermission('accounting.manage')||$u->hasPermission('products.view'))<div class="nav-caption">Финансы и товары</div>@endif
@if($u->hasPermission('cash.view'))<a class="{{ request()->routeIs('admin.finance.*')?'active':'' }}" href="{{ route('admin.finance.index') }}"><i class="bi bi-cash-stack"></i>Касса и платежи</a>@endif
@if($u->hasPermission('accounting.manage'))<a class="{{ request()->routeIs('admin.accounting.*')?'active':'' }}" href="{{ route('admin.accounting.index') }}"><i class="bi bi-arrow-left-right"></i>Обмен с 1С</a>@endif
@if($u->hasPermission('products.view'))<a class="{{ request()->routeIs('admin.products.*')?'active':'' }}" href="{{ route('admin.products.index') }}"><i class="bi bi-ticket-perforated"></i>Товары и тарифы</a>@endif
@if($u->hasPermission('inventory.view'))<a class="{{ request()->routeIs('admin.inventory.*')?'active':'' }}" href="{{ route('admin.inventory.index') }}"><i class="bi bi-box-seam"></i>Склад и партии</a>@endif

@if($u->hasPermission('staff.view')||$u->hasPermission('training.manage')||$u->hasPermission('content.manage'))<div class="nav-caption">Персонал</div>@endif
@if($u->hasPermission('content.manage'))<a class="{{ request()->routeIs('admin.trainers.*')?'active':'' }}" href="{{ route('admin.trainers.index') }}"><i class="bi bi-person-badge"></i>Тренеры</a>@endif
@if($u->hasPermission('training.manage'))<a class="{{ request()->routeIs('admin.training-plans.*')?'active':'' }}" href="{{ route('admin.training-plans.index') }}"><i class="bi bi-clipboard2-pulse"></i>Планы тренировок</a>@endif
@if($u->hasPermission('staff.view'))<a class="{{ request()->routeIs('admin.staff.*')?'active':'' }}" href="{{ route('admin.staff.index') }}"><i class="bi bi-calendar3"></i>Графики и зарплата</a>@endif

@if($u->hasPermission('reports.view')||$u->hasPermission('audit.view')||$u->hasPermission('permissions.manage'))<div class="nav-caption">Управление</div>@endif
@if($u->hasPermission('reports.view'))<a class="{{ request()->routeIs('admin.reports.*')?'active':'' }}" href="{{ route('admin.reports.index') }}"><i class="bi bi-bar-chart-line"></i>Отчёты и KPI</a>@endif
@if($u->hasPermission('audit.view'))<a class="{{ request()->routeIs('admin.audit.*')?'active':'' }}" href="{{ route('admin.audit.index') }}"><i class="bi bi-journal-text"></i>Аудит действий</a>@endif
@if($u->hasPermission('permissions.manage'))<a class="{{ request()->routeIs('admin.permissions.*')?'active':'' }}" href="{{ route('admin.permissions.index') }}"><i class="bi bi-person-lock"></i>Роли и права</a>@endif

@if($u->hasPermission('content.manage'))<div class="nav-caption">Сайт</div><a class="{{ request()->routeIs('admin.slides.*')?'active':'' }}" href="{{ route('admin.slides.index') }}"><i class="bi bi-card-image"></i>Слайдер</a><a class="{{ request()->routeIs('admin.news.*')?'active':'' }}" href="{{ route('admin.news.index') }}"><i class="bi bi-newspaper"></i>Новости</a><a class="{{ request()->routeIs('admin.gallery.*')?'active':'' }}" href="{{ route('admin.gallery.index') }}"><i class="bi bi-images"></i>Фотогалерея</a>@endif
@if($u->hasPermission('settings.manage')||$u->hasPermission('seo.manage'))<div class="nav-caption">Настройки</div>@endif
@if($u->hasPermission('settings.manage'))<a class="{{ request()->routeIs('admin.settings.general*')?'active':'' }}" href="{{ route('admin.settings.general') }}"><i class="bi bi-sliders"></i>Настройки сайта</a><a class="{{ request()->routeIs('admin.settings.contacts*')?'active':'' }}" href="{{ route('admin.settings.contacts') }}"><i class="bi bi-telephone"></i>Контакты и реквизиты</a>@endif
@if($u->hasPermission('seo.manage'))<a class="{{ request()->routeIs('admin.seo.*')?'active':'' }}" href="{{ route('admin.seo.index') }}"><i class="bi bi-search"></i>SEO</a>@endif
</nav><div class="sidebar-bottom"><a href="{{ route('home') }}" target="_blank"><i class="bi bi-box-arrow-up-right"></i>Открыть сайт</a><form method="post" action="{{ route('logout') }}">@csrf<button><i class="bi bi-box-arrow-left"></i>Выйти</button></form></div></aside>
<div class="admin-main"><header class="admin-header"><button class="sidebar-toggle" type="button" onclick="document.body.classList.toggle('sidebar-open')"><i class="bi bi-list"></i></button><div><small>@yield('eyebrow',$site['site_name'])</small><h1>@yield('heading','CRM')</h1></div><div class="admin-user"><span>{{ mb_substr($u->name,0,1) }}</span><div><strong>{{ $u->name }}</strong><small>{{ $u->roleLabel() }}</small></div></div></header><main class="admin-content">@if(session('success'))<div class="alert alert-success border-0 shadow-sm rounded-4">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger border-0 shadow-sm rounded-4"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>@stack('scripts')</body></html>
