@extends('admin.layout')
@section('title','Отчёты') @section('heading','Отчёты и KPI') @section('eyebrow','Аналитика бассейна и бизнеса')
@section('content')
<form class="row g-2 mb-4"><div class="col-auto"><input type="date" class="form-control" name="from" value="{{ $from->format('Y-m-d') }}"></div><div class="col-auto"><input type="date" class="form-control" name="to" value="{{ $to->format('Y-m-d') }}"></div><div class="col-auto"><button class="btn btn-primary">Пересчитать</button></div></form>
<div class="row g-3 mb-4"><div class="col-md-6 col-xl-3"><div class="pool-kpi"><i class="bi bi-currency-ruble"></i><strong>{{ number_format($revenue,0,',',' ') }} ₽</strong><small>оплаченная выручка</small></div></div><div class="col-md-6 col-xl-3"><div class="pool-kpi"><i class="bi bi-person-check"></i><strong>{{ $visits->count() }}</strong><small>посещений</small></div></div><div class="col-md-6 col-xl-3"><div class="pool-kpi"><i class="bi bi-person-vcard"></i><strong>{{ $activeMemberships }}</strong><small>активных членств</small></div></div><div class="col-md-6 col-xl-3"><div class="pool-kpi"><i class="bi bi-speedometer"></i><strong>{{ $capacity?round($booked/$capacity*100):0 }}%</strong><small>средняя загрузка сеансов</small></div></div></div>
<div class="row g-4 mb-4"><div class="col-xl-7"><div class="admin-card p-4"><h3>Выручка и посещаемость по дням</h3><div class="chart-box"><canvas id="dailyChart"></canvas></div></div></div><div class="col-xl-5"><div class="admin-card p-4"><h3>Загрузка по часам</h3><div class="chart-box"><canvas id="hoursChart"></canvas></div></div></div></div>
<div class="row g-4"><div class="col-xl-6"><div class="admin-card p-4"><h3>Услуги</h3><table class="table mini-table"><thead><tr><th>Услуга</th><th>Записей</th><th class="text-end">Сумма</th></tr></thead><tbody>@foreach($services as $name=>$stat)<tr><td>{{ $name }}</td><td>{{ $stat['bookings'] }}</td><td class="text-end">{{ number_format($stat['revenue'],0,',',' ') }} ₽</td></tr>@endforeach</tbody></table></div></div><div class="col-xl-6"><div class="admin-card p-4"><h3>Эффективность тренеров</h3><table class="table mini-table"><thead><tr><th>Тренер</th><th>Занятий</th><th>Клиентов</th><th class="text-end">Сумма</th></tr></thead><tbody>@foreach($trainers as $name=>$stat)<tr><td>{{ $name }}</td><td>{{ $stat['bookings'] }}</td><td>{{ $stat['people'] }}</td><td class="text-end">{{ number_format($stat['revenue'],0,',',' ') }} ₽</td></tr>@endforeach</tbody></table></div></div></div>
@endsection
@push('scripts')
@php($labels=$dailyRevenue->keys()->merge($dailyVisits->keys())->unique()->sort()->values())
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>
const labels=@json($labels);const revenue=@json($labels->map(fn($d)=>(float)($dailyRevenue[$d]??0)));const visits=@json($labels->map(fn($d)=>(int)($dailyVisits[$d]??0)));
new Chart(document.getElementById('dailyChart'),{type:'line',data:{labels,datasets:[{label:'Выручка, ₽',data:revenue,yAxisID:'y'},{label:'Посещения',data:visits,yAxisID:'y1'}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true},y1:{beginAtZero:true,position:'right',grid:{drawOnChartArea:false}}}}});
const hourLabels=@json($hours->keys()->values());const hourBooked=@json($hours->values()->map(fn($x)=>$x['booked']));const hourCapacity=@json($hours->values()->map(fn($x)=>$x['capacity']));new Chart(document.getElementById('hoursChart'),{type:'bar',data:{labels:hourLabels,datasets:[{label:'Записано',data:hourBooked},{label:'Вместимость',data:hourCapacity}]},options:{responsive:true,maintainAspectRatio:false}});
</script>
@endpush
