@extends('workspace')
@section('title','Ресепшен') @section('workspace_name','Ресепшен')
@section('content')
<div class="admin-card p-4 mb-4"><form id="searchForm" method="get" action="{{ route('reception.index') }}" class="row g-2"><div class="col-lg-9"><div class="input-group"><span class="input-group-text px-4"><i class="bi bi-search fs-4"></i></span><input autofocus autocomplete="off" class="form-control big-search" id="receptionSearch" name="q" value="{{ $query }}" placeholder="ФИО, телефон, email, QR / NFC-код"></div></div><div class="col-lg-2"><button class="btn btn-primary w-100 h-100 fs-5">Найти клиента</button></div><div class="col-lg-1"><button type="button" id="scanQr" class="btn btn-outline-primary w-100 h-100" title="Сканировать QR камерой"><i class="bi bi-qr-code-scan fs-3"></i></button></div></form><video id="qrVideo" class="w-100 rounded-4 mt-3 d-none" style="max-height:300px;background:#111" playsinline></video><div class="small text-muted mt-2">Аппаратный QR/NFC-сканер можно использовать как клавиатуру: отсканируйте код и нажмите Enter.</div></div>
@if($results->count()>1 && !$customer)<div class="admin-card p-3 mb-4"><h4>Найдено: {{ $results->count() }}</h4><div class="list-group list-group-flush">@foreach($results as $c)<a class="list-group-item list-group-item-action py-3 d-flex justify-content-between" href="{{ route('reception.index',['q'=>$query,'customer'=>$c->id]) }}"><span><strong>{{ $c->name }}</strong><small class="d-block text-muted">{{ $c->phone }} · {{ $c->email }}</small></span><i class="bi bi-chevron-right"></i></a>@endforeach</div></div>@endif
@if($customer)
<div class="row g-4 mb-4"><div class="col-xl-4"><div class="admin-card p-4 h-100"><div class="d-flex gap-3 align-items-center">@if($customer->photo_path)<img class="customer-photo" src="{{ Storage::url($customer->photo_path) }}" alt="">@else<div class="customer-photo">{{ mb_substr($customer->name,0,1) }}</div>@endif<div><h2 class="mb-1">{{ $customer->name }}</h2><div class="text-muted">{{ $customer->phone }}</div><div class="text-muted">{{ $customer->email }}</div></div></div><hr><div class="small text-muted">Карты доступа</div><div class="d-flex flex-wrap gap-1 mt-1">@forelse($customer->accessCards as $card)<span class="badge text-bg-light border">{{ strtoupper($card->type) }} · {{ $card->code }}</span>@empty<span class="text-muted">нет</span>@endforelse</div></div></div>
<div class="col-xl-8"><div class="row g-3 h-100"><div class="col-sm-6"><div class="status-tile"><small class="text-muted">Абонемент</small>@if($status['membership'])<h4 class="text-success mt-2">{{ $status['membership']->plan?->name ?? $status['membership']->number }}</h4><div>{{ $status['membership']->number }}</div><small>до {{ $status['membership']->ends_on?->format('d.m.Y') }}</small>@else<h4 class="text-danger mt-2">Нет активного</h4>@endif</div></div><div class="col-sm-6"><div class="status-tile"><small class="text-muted">Медицинский допуск</small>@if($status['blockedMedical'])<h4 class="text-danger mt-2"><i class="bi bi-x-octagon"></i> Вход заблокирован</h4><small>{{ $status['blockedMedical']->blocked_reason ?: $status['blockedMedical']->status }}</small>@elseif($status['medical'])<h4 class="text-success mt-2"><i class="bi bi-check-circle"></i> Допущен</h4><small>до {{ $status['medical']->expires_on?->format('d.m.Y') ?: 'без срока' }}</small>@else<h4 class="text-warning mt-2">Нет действующей справки</h4>@endif</div></div><div class="col-sm-6"><div class="status-tile"><small class="text-muted">Задолженность</small><h3 class="mt-2 {{ $status['debt']>0?'text-danger':'text-success' }}">{{ number_format($status['debt'],0,',',' ') }} ₽</h3><small>{{ $status['debt']>0?'Есть неоплаченные заказы':'Задолженности нет' }}</small></div></div><div class="col-sm-6"><div class="status-tile"><small class="text-muted">Шкафчик</small>@if($status['rental'])<h3 class="mt-2">№ {{ $status['rental']->locker?->number }}</h3><small>{{ $status['rental']->locker?->zone }}</small>@else<h4 class="mt-2 text-muted">Не выдан</h4>@endif</div></div></div></div></div>
<div class="row g-4"><div class="col-xl-7"><div class="admin-card p-4"><h3>Проход</h3><form method="post" action="{{ route('admin.access.checkin') }}" class="row g-3">@csrf<input type="hidden" name="customer_id" value="{{ $customer->id }}"><input type="hidden" name="event_type" value="enter"><div class="col-md-8"><select class="form-select form-select-lg" name="pool_zone_id" required><option value="">Выберите зону</option>@foreach($zones as $zone)<option value="{{ $zone->id }}">{{ $zone->name }}</option>@endforeach</select></div><div class="col-md-4"><button class="btn btn-success btn-lg w-100" {{ $status['blockedMedical']?'disabled':'' }}><i class="bi bi-door-open"></i> Пропустить</button></div></form><form method="post" action="{{ route('admin.access.checkin') }}" class="mt-2">@csrf<input type="hidden" name="customer_id" value="{{ $customer->id }}"><input type="hidden" name="event_type" value="exit"><input type="hidden" name="pool_zone_id" value="{{ $zones->first()?->id }}"><button class="btn btn-outline-secondary">Зарегистрировать выход</button></form><hr><h4>Записи на сегодня</h4>@forelse($customer->bookings as $b)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $b->service?->name }}</span><strong>{{ $b->slot?->starts_at?->format('H:i') }}</strong></div>@empty<p class="text-muted">Записей на сегодня нет.</p>@endforelse</div></div>
<div class="col-xl-5"><div class="admin-card p-4"><h3>Шкафчик</h3>@if(!$status['rental'])<form method="post" action="{{ route('admin.access.lockers.assign') }}" class="row g-2">@csrf<input type="hidden" name="customer_id" value="{{ $customer->id }}"><div class="col-8"><select class="form-select" name="locker_id" required><option value="">Свободный шкафчик</option>@foreach($availableLockers as $locker)<option value="{{ $locker->id }}">№ {{ $locker->number }} · {{ $locker->zone }}</option>@endforeach</select></div><div class="col-4"><input type="number" class="form-control" name="deposit" value="0" placeholder="Залог"></div><div class="col-12"><button class="btn btn-primary w-100">Выдать шкафчик</button></div></form>@else<form method="post" action="{{ route('admin.access.lockers.return',$status['rental']) }}">@csrf<button class="btn btn-outline-danger w-100">Вернуть шкафчик № {{ $status['rental']->locker?->number }}</button></form>@endif</div></div></div>
@elseif($query!=='' && $results->isEmpty())<div class="alert alert-warning rounded-4">Клиент не найден.</div>@endif
@endsection
@push('scripts')<script>
const scanBtn=document.getElementById('scanQr'),video=document.getElementById('qrVideo'),input=document.getElementById('receptionSearch');let stream=null;
scanBtn?.addEventListener('click',async()=>{if(!('BarcodeDetector' in window)){alert('Камерное распознавание QR не поддерживается этим браузером. Используйте аппаратный сканер QR/NFC.');return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=stream;video.classList.remove('d-none');await video.play();const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{if(!stream)return;const codes=await detector.detect(video);if(codes.length){input.value=codes[0].rawValue;stream.getTracks().forEach(t=>t.stop());stream=null;video.classList.add('d-none');document.getElementById('searchForm').submit();return;}requestAnimationFrame(tick)};tick();}catch(e){alert('Не удалось открыть камеру: '+e.message);}});
</script>@endpush
