@extends('layouts.app')
@section('title', 'Билеты и абонементы — Комплекс Греция')
@section('content')
<section class="page-hero"><div class="container"><div class="eyebrow">Онлайн-витрина</div><h1>Билеты и абонементы</h1><p>Выберите подходящий вариант. После оплаты электронный код появится в заказе.</p></div></section>
<section class="section-padding pt-4"><div class="container"><div class="row g-4">
@forelse($products as $product)
<div class="col-md-6 col-xl-4"><div class="catalog-card h-100"><div class="catalog-top"><span class="ticket-type">{{ $product->type === 'subscription' ? 'Абонемент' : ($product->type === 'gift' ? 'Подарочный' : 'Разовый билет') }}</span><span class="catalog-icon"><i class="bi {{ $product->type === 'gift' ? 'bi-gift' : 'bi-ticket-perforated' }}"></i></span></div><h2>{{ $product->name }}</h2><p>{{ $product->description }}</p><ul>@if($product->visits_count)<li><i class="bi bi-check2"></i> {{ $product->visits_count }} посещений</li>@endif<li><i class="bi bi-check2"></i> Срок действия {{ $product->validity_days }} дней</li><li><i class="bi bi-check2"></i> Электронный код билета</li></ul><div class="catalog-bottom"><strong>{{ number_format($product->price, 0, ',', ' ') }} ₽</strong><button class="btn btn-primary rounded-pill buy-button" data-bs-toggle="modal" data-bs-target="#buyModal" data-product-id="{{ $product->id }}" data-product-name="{{ $product->name }}" data-product-price="{{ number_format($product->price, 0, ',', ' ') }}">Купить</button></div></div></div>
@empty<div class="col-12"><div class="alert alert-light rounded-4">Каталог пока пуст. Администратор может добавить товары в CRM.</div></div>@endforelse
</div></div></section>
<div class="modal fade" id="buyModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 rounded-5 overflow-hidden"><div class="modal-header border-0 px-4 pt-4"><div><small class="text-primary fw-bold text-uppercase">Оформление заказа</small><h3 class="modal-title" id="modalProductName">Билет</h3></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form method="post" action="{{ route('order.store') }}">@csrf<div class="modal-body px-4"><input type="hidden" name="product_id" id="modalProductId"><div class="row g-3"><div class="col-12"><label class="form-label">Имя</label><input class="form-control form-control-lg" name="name" value="{{ old('name') }}" required></div><div class="col-md-6"><label class="form-label">Телефон</label><input class="form-control form-control-lg" name="phone" value="{{ old('phone') }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control form-control-lg" name="email" value="{{ old('email') }}" required></div><div class="col-4"><label class="form-label">Количество</label><input type="number" class="form-control form-control-lg" name="quantity" value="1" min="1" max="10" required></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="privacy" value="1" id="privacyOrder" required><label class="form-check-label small text-muted" for="privacyOrder">Согласен с <a href="{{ route('privacy') }}">обработкой данных</a> и <a href="{{ route('offer') }}">офертой</a></label></div></div></div></div><div class="modal-footer border-0 px-4 pb-4"><button class="btn btn-primary btn-lg w-100 rounded-pill" type="submit">Создать заказ · <span id="modalProductPrice"></span> ₽</button><small class="text-muted text-center w-100">Сейчас используется ручное подтверждение оплаты. Эквайринг подключается через конфигурацию.</small></div></form></div></div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('.buy-button').forEach(button => button.addEventListener('click', () => {document.getElementById('modalProductId').value = button.dataset.productId;document.getElementById('modalProductName').textContent = button.dataset.productName;document.getElementById('modalProductPrice').textContent = button.dataset.productPrice;}));</script>@endpush
