@extends('admin.layout')
@section('title','Динамические цены')
@section('heading','Динамическое ценообразование')
@section('eyebrow','Непиковые часы, выходные, загрузка и льготные сегменты')
@section('content')
<div class="admin-card p-4 mb-4"><h3>Новое правило</h3><p class="text-muted">Для процента используйте отрицательное значение для скидки и положительное для наценки: например -20 или +15.</p><form method="post" action="{{ route('admin.pricing.store') }}" class="row g-2">@csrf
<div class="col-md-4"><input class="form-control" name="name" placeholder="Утро -20%" required></div><div class="col-md-2"><select class="form-select" name="target_type"><option value="service">Услуга</option><option value="product">Товар</option></select></div><div class="col-md-3"><select class="form-select" name="service_id"><option value="">Все услуги</option>@foreach($services as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></div><div class="col-md-3"><select class="form-select" name="product_id"><option value="">Все товары</option>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></div>
<div class="col-md-2"><select class="form-select" name="customer_segment"><option value="all">Все</option><option value="child">Дети</option><option value="senior">Пенсионеры 60+</option><option value="family">Семьи</option><option value="corporate">Корпоративные</option></select></div><div class="col-md-2"><input type="time" class="form-control" name="time_from" title="Время с"></div><div class="col-md-2"><input type="time" class="form-control" name="time_to" title="Время до"></div><div class="col-md-2"><input type="number" step="0.1" min="0" max="100" class="form-control" name="occupancy_min_pct" placeholder="Загрузка от %"></div><div class="col-md-2"><input type="number" step="0.1" min="0" max="100" class="form-control" name="occupancy_max_pct" placeholder="Загрузка до %"></div><div class="col-md-2"><input type="number" class="form-control" name="priority" value="100" title="Приоритет"></div>
<div class="col-12"><div class="d-flex flex-wrap gap-3 small">@foreach([1=>'Пн',2=>'Вт',3=>'Ср',4=>'Чт',5=>'Пт',6=>'Сб',7=>'Вс'] as $n=>$day)<label><input type="checkbox" name="weekdays[]" value="{{ $n }}"> {{ $day }}</label>@endforeach</div></div>
<div class="col-md-2"><select class="form-select" name="adjustment_type"><option value="percent">Процент %</option><option value="fixed">Сумма +/-</option><option value="override">Фиксированная цена</option></select></div><div class="col-md-2"><input type="number" step="0.01" class="form-control" name="adjustment_value" value="-10" required></div><div class="col-md-2"><input type="number" step="0.01" class="form-control" name="min_price" placeholder="Мин. цена"></div><div class="col-md-2"><input type="number" step="0.01" class="form-control" name="max_price" placeholder="Макс. цена"></div><div class="col-md-2"><input type="date" class="form-control" name="starts_on"></div><div class="col-md-2"><input type="date" class="form-control" name="ends_on"></div>
<div class="col-md-3"><div class="form-check form-switch mt-2"><input class="form-check-input" type="checkbox" name="combinable" value="1" checked><label class="form-check-label">Сочетается с другими</label></div></div><div class="col-md-3"><div class="form-check form-switch mt-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><label class="form-check-label">Активно</label></div></div><div class="col-md-3"><button class="btn btn-primary w-100">Создать правило</button></div></form></div>
<div class="admin-card p-4"><h3>Правила</h3><div class="table-responsive"><table class="table mini-table align-middle"><thead><tr><th>Приоритет</th><th>Правило</th><th>Цель</th><th>Сегмент</th><th>Когда</th><th>Изменение</th><th>Статус</th><th></th></tr></thead><tbody>@forelse($rules as $r)<tr><td>{{ $r->priority }}</td><td><strong>{{ $r->name }}</strong></td><td>{{ $r->target_type==='service' ? ($r->service?->name ?? 'Все услуги') : ($r->product?->name ?? 'Все товары') }}</td><td>{{ $r->customer_segment }}</td><td><small>@if($r->weekdays)Дни: {{ implode(',',$r->weekdays) }}<br>@endif @if($r->time_from || $r->time_to){{ $r->time_from ?: '00:00' }}–{{ $r->time_to ?: '23:59' }}<br>@endif @if($r->occupancy_min_pct!==null || $r->occupancy_max_pct!==null)Загрузка {{ $r->occupancy_min_pct ?? 0 }}–{{ $r->occupancy_max_pct ?? 100 }}%@endif</small></td><td><strong>{{ $r->adjustment_type }}</strong> {{ $r->adjustment_value }}</td><td><span class="badge {{ $r->is_active?'text-bg-success':'text-bg-secondary' }}">{{ $r->is_active?'вкл':'выкл' }}</span></td><td><form method="post" action="{{ route('admin.pricing.destroy',$r) }}" onsubmit="return confirm('Удалить правило?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Правил пока нет.</td></tr>@endforelse</tbody></table></div></div>
@endsection
