@extends('admin.layout')
@section('title',$customer->name) @section('heading','Клиент 360°') @section('eyebrow',$customer->name)
@section('content')
<div class="row g-4 mb-4">
<div class="col-xl-4"><div class="admin-card p-4 h-100"><div class="d-flex gap-3 align-items-center"><div class="rounded-circle bg-light d-flex align-items-center justify-content-center overflow-hidden" style="width:84px;height:84px">@if($customer->photo_path)<img src="{{ asset('storage/'.$customer->photo_path) }}" class="w-100 h-100 object-fit-cover">@else<span class="fs-2 fw-bold">{{ mb_substr($customer->name,0,1) }}</span>@endif</div><div><h3 class="mb-1">{{ $customer->name }}</h3><span class="badge text-bg-light border">{{ $customer->source }}</span>@if($preferredTrainer)<small class="d-block mt-1">Тренер: {{ $preferredTrainer->name }}</small>@endif</div></div><hr>
@if($canPersonal)<div class="small"><div><strong>Телефон:</strong> {{ $customer->phone }}</div><div><strong>Email:</strong> {{ $customer->email?:'—' }}</div><div><strong>Дата рождения:</strong> {{ $customer->birth_date?->format('d.m.Y')?:'—' }} @if($customer->age())({{ $customer->age() }} лет)@endif</div><div><strong>Экстренный контакт:</strong> {{ $customer->emergency_contact?:'—' }}</div></div>@else<div class="alert alert-secondary mb-0">Персональные данные скрыты текущими правами.</div>@endif
<hr><div class="row text-center"><div class="col"><strong class="d-block fs-5">{{ $customer->visits->count() }}</strong><small>визитов</small></div><div class="col"><strong class="d-block fs-5">{{ $customer->bookings->count() }}</strong><small>записей</small></div><div class="col"><strong class="d-block fs-5">{{ $customer->orders->count() }}</strong><small>заказов</small></div></div></div></div>
<div class="col-xl-8"><div class="row g-3 h-100">
<div class="col-md-4"><div class="admin-card p-3 h-100"><small class="text-muted">Депозит</small><div class="fs-3 fw-bold">{{ number_format((float)optional($customer->wallet)->deposit_balance,0,',',' ') }} ₽</div><small>Бонусы: {{ number_format((float)optional($customer->wallet)->bonus_balance,0,',',' ') }}</small></div></div>
<div class="col-md-4"><div class="admin-card p-3 h-100"><small class="text-muted">Неоплачено</small><div class="fs-3 fw-bold {{ $debt>0?'text-danger':'' }}">{{ number_format($debt,0,',',' ') }} ₽</div><small>{{ $customer->orders->whereNotIn('payment_status',['paid','refunded'])->count() }} заказ(а)</small></div></div>
<div class="col-md-4"><div class="admin-card p-3 h-100"><small class="text-muted">Активные членства</small><div class="fs-3 fw-bold">{{ $customer->memberships->where('status','active')->count() }}</div><small>Последний визит: {{ $customer->last_visit_at?->format('d.m.Y H:i')?:'—' }}</small></div></div>
<div class="col-12"><div class="admin-card p-3"><h5>Семья и дети</h5>@forelse($customer->families as $family)<a class="badge text-bg-light border text-decoration-none p-2" href="{{ route('admin.families.show',$family) }}">{{ $family->name }} · {{ $family->members->count() }} чел.</a>@empty<span class="text-muted">Не привязан к семейному аккаунту</span>@endforelse</div></div>
</div></div></div>

<div class="admin-card p-4 mb-4"><ul class="nav nav-pills gap-2" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#timeline">История</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#memberships">Абонементы</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#bookings">Записи</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#sales">Покупки</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#training">Тренировки</button></li>@if(auth()->user()->hasPermission('medical.view'))<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#medical">Медицина</button></li>@endif<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#notes">Заметки и цели</button></li></ul></div>

<div class="tab-content">
<div class="tab-pane fade show active" id="timeline"><div class="admin-card p-4"><h3>Единая хронология</h3>@php($events=collect())
@foreach($customer->visits as $v)@php($events->push(['at'=>$v->visited_at,'title'=>'Посещение','text'=>$v->notes?:$v->source,'icon'=>'bi-door-open']))@endforeach
@foreach($customer->interactions as $i)@php($events->push(['at'=>$i->occurred_at,'title'=>'Контакт · '.$i->channel,'text'=>trim(($i->subject??'').' '.($i->body??'')),'icon'=>'bi-chat-left-text']))@endforeach
@foreach($customer->bookings as $b)@php($events->push(['at'=>$b->created_at,'title'=>'Запись · '.($b->service?->name??''),'text'=>($b->slot?->starts_at?->format('d.m.Y H:i')??'').' · '.$b->status,'icon'=>'bi-calendar-check']))@endforeach
@foreach($customer->orders as $o)@php($events->push(['at'=>$o->created_at,'title'=>'Заказ '.$o->number,'text'=>number_format($o->total,0,',',' ').' ₽ · '.$o->payment_status,'icon'=>'bi-receipt']))@endforeach
@foreach($customer->staffNotes as $n)@php($events->push(['at'=>$n->created_at,'title'=>'Заметка · '.$n->type,'text'=>$n->body.' · '.($n->user?->name??''),'icon'=>'bi-sticky']))@endforeach
@forelse($events->sortByDesc('at')->take(100) as $e)<div class="d-flex gap-3 border-bottom py-3"><i class="bi {{ $e['icon'] }} fs-4"></i><div><strong>{{ $e['title'] }}</strong><small class="d-block text-muted">{{ optional($e['at'])->format('d.m.Y H:i') }}</small><div>{{ $e['text'] }}</div></div></div>@empty<p class="text-muted">История пока пуста.</p>@endforelse</div></div>

<div class="tab-pane fade" id="memberships"><div class="admin-card p-4"><h3>Абонементы и заморозки</h3><div class="table-responsive"><table class="table"><thead><tr><th>Номер</th><th>Тариф</th><th>Срок</th><th>Остаток</th><th>Статус</th></tr></thead><tbody>@foreach($customer->memberships as $m)<tr><td>{{ $m->number }}</td><td>{{ $m->plan?->name }} @if($m->family)<small class="d-block">Семья: {{ $m->family->name }}</small>@endif</td><td>{{ $m->starts_on->format('d.m.Y') }}–{{ $m->ends_on->format('d.m.Y') }}</td><td>{{ $m->visits_total===null?'∞':max(0,$m->visits_total-$m->visits_used) }}</td><td>{{ $m->status }} @foreach($m->freezes as $f)<small class="d-block">заморозка {{ $f->starts_on->format('d.m') }}–{{ $f->ends_on->format('d.m') }}</small>@endforeach</td></tr>@endforeach</tbody></table></div></div></div>

<div class="tab-pane fade" id="bookings"><div class="admin-card p-4"><h3>Записи и посещения</h3><div class="table-responsive"><table class="table"><thead><tr><th>Дата</th><th>Услуга</th><th>Тренер</th><th>Статус</th></tr></thead><tbody>@foreach($customer->bookings->sortByDesc(fn($b)=>$b->slot?->starts_at) as $b)<tr><td>{{ $b->slot?->starts_at?->format('d.m.Y H:i') }}</td><td>{{ $b->service?->name }}</td><td>{{ $b->trainer?->name }}</td><td>{{ $b->status }}</td></tr>@endforeach</tbody></table></div></div></div>

<div class="tab-pane fade" id="sales"><div class="row g-4"><div class="col-xl-8"><div class="admin-card p-4"><h3>Заказы</h3>@foreach($customer->orders as $o)<div class="border-bottom py-2"><strong>{{ $o->number }}</strong> · {{ number_format($o->total,0,',',' ') }} ₽ <span class="badge text-bg-light">{{ $o->payment_status }}</span><small class="d-block">@foreach($o->items as $item){{ $item->name }} × {{ $item->quantity }}; @endforeach</small></div>@endforeach</div></div><div class="col-xl-4"><div class="admin-card p-4"><h3>Сертификаты</h3>@foreach($customer->certificates as $c)<div class="border-bottom py-2"><strong>{{ $c->serial }}</strong><small class="d-block">{{ number_format($c->amount,0,',',' ') }} ₽ · {{ $c->status }}</small></div>@endforeach</div></div></div></div>

<div class="tab-pane fade" id="training"><div class="row g-4"><div class="col-xl-7"><div class="admin-card p-4"><h3>Планы тренировок</h3>@foreach($customer->trainingPlans as $p)<div class="border rounded-3 p-3 mb-2"><strong>{{ $p->title }}</strong><small class="d-block">{{ $p->trainer?->name }} · {{ $p->status }}</small><div>{{ $p->goal }}</div></div>@endforeach</div></div><div class="col-xl-5"><div class="admin-card p-4"><h3>Школа плавания</h3>@foreach($customer->swimGroupMemberships as $m)<div class="border-bottom py-2"><strong>{{ $m->group?->name }}</strong><small class="d-block">{{ $m->group?->trainer?->name }} · {{ $m->status }}</small>@foreach($m->progress->take(3) as $p)<div class="small">{{ $p->recorded_on->format('d.m.Y') }} · {{ $p->skill }} · {{ $p->score }}/5</div>@endforeach</div>@endforeach</div></div></div></div>

@if(auth()->user()->hasPermission('medical.view'))<div class="tab-pane fade" id="medical"><div class="admin-card p-4"><h3>Медицинские допуски</h3>@foreach($customer->medicalClearances as $m)<div class="border rounded-3 p-3 mb-2"><div class="d-flex justify-content-between"><strong>{{ $m->type }}</strong><span class="badge {{ $m->isValid()?'text-bg-success':'text-bg-danger' }}">{{ $m->status }}</span></div><small>Срок: {{ $m->expires_on?->format('d.m.Y')?:'без срока' }} @if($m->access_blocked) · ВХОД ЗАБЛОКИРОВАН: {{ $m->blocked_reason }} @endif</small>@if($m->restrictions)<div class="mt-2"><strong>Ограничения:</strong> {{ $m->restrictions }}</div>@endif</div>@endforeach</div></div>@endif

<div class="tab-pane fade" id="notes"><div class="row g-4"><div class="col-xl-7"><div class="admin-card p-4"><h3>Заметки персонала</h3>@foreach($customer->staffNotes as $n)<div class="border-bottom py-3"><span class="badge text-bg-light">{{ $n->type }}</span> {{ $n->body }}<small class="d-block text-muted">{{ $n->user?->name }} · {{ $n->created_at->format('d.m.Y H:i') }}</small></div>@endforeach@if(auth()->user()->hasPermission('customers.notes'))<form method="post" action="{{ route('admin.customers.notes.store',$customer) }}" class="row g-2 mt-3">@csrf<div class="col-md-3"><select class="form-select" name="type"><option value="note">Общее</option><option value="service">Сервис</option><option value="sales">Продажи</option><option value="trainer">Тренер</option><option value="complaint">Жалоба</option></select></div><div class="col-md-7"><textarea class="form-control" name="body" required placeholder="Комментарий"></textarea></div><div class="col-md-2"><button class="btn btn-primary w-100">Добавить</button></div></form>@endif</div></div><div class="col-xl-5"><div class="admin-card p-4"><h3>Цели</h3>@foreach($customer->goals as $g)<div class="border rounded-3 p-3 mb-2"><strong>{{ $g->title }}</strong><div class="progress my-2" style="height:8px"><div class="progress-bar" style="width:{{ $g->progress_percent }}%"></div></div><small>{{ $g->progress_percent }}% · {{ $g->status }} @if($g->trainer)· {{ $g->trainer->name }}@endif</small></div>@endforeach@if(auth()->user()->hasPermission('customers.notes'))<form method="post" action="{{ route('admin.customers.goals.store',$customer) }}" class="row g-2 mt-3">@csrf<div class="col-12"><input class="form-control" name="title" placeholder="Цель" required></div><div class="col-7"><select class="form-select" name="trainer_id"><option value="">Без тренера</option>@foreach($trainers as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></div><div class="col-5"><input type="number" min="0" max="100" value="0" class="form-control" name="progress_percent"></div><div class="col-12"><textarea class="form-control" name="description" placeholder="Описание"></textarea></div><div class="col-12"><button class="btn btn-dark">Создать цель</button></div></form>@endif</div></div></div></div>
</div>
@endsection
