@extends('admin.layout')
@section('title','Интеграция с 1С')
@section('heading','1С:Бухгалтерия')
@section('eyebrow','Продажи, оплаты, возвраты, касса и номенклатура')
@section('content')
@php($i=$integration)
<div class="row g-4 mb-4">
<div class="col-xl-7"><div class="admin-card p-4"><h3>Подключение</h3><p class="text-muted">Рекомендуемый вариант: опубликованный HTTP-сервис в 1С и приём JSON/XML. Версия EnterpriseData хранится как параметр совместимости адаптера.</p><form method="post" action="{{ route('admin.accounting.update') }}" class="row g-3">@csrf @method('put')
<div class="col-md-6"><label class="form-label">Название</label><input class="form-control" name="name" value="{{ old('name',$i?->name ?? '1С:Бухгалтерия') }}" required></div>
<div class="col-md-3"><label class="form-label">Транспорт</label><select class="form-select" name="driver"><option value="json_http" @selected(($i?->driver??'json_http')==='json_http')>HTTP JSON</option><option value="xml_http" @selected($i?->driver==='xml_http')>HTTP XML</option></select></div>
<div class="col-md-3"><label class="form-label">EnterpriseData</label><input class="form-control" name="format_version" value="{{ old('format_version',$i?->format_version ?? '1.23') }}"></div>
<div class="col-12"><label class="form-label">URL HTTP-сервиса 1С</label><input type="url" class="form-control" name="endpoint_url" value="{{ old('endpoint_url',$i?->endpoint_url) }}" placeholder="https://1c.example.ru/hs/greecya/accounting"></div>
<div class="col-md-4"><label class="form-label">Логин</label><input class="form-control" name="username" value="{{ old('username',$i?->username) }}"></div><div class="col-md-4"><label class="form-label">Пароль</label><input type="password" class="form-control" name="password" placeholder="не менять"></div><div class="col-md-4"><label class="form-label">Token / HMAC secret</label><input type="password" class="form-control" name="token" placeholder="не менять"></div>
<div class="col-md-6"><label class="form-label">Код организации</label><input class="form-control" name="organization_code" value="{{ old('organization_code',$i?->organization_code) }}"></div><div class="col-md-3"><label class="form-label">Timeout, сек</label><input type="number" min="5" max="120" class="form-control" name="timeout" value="{{ old('timeout',$i?->options['timeout'] ?? 30) }}"></div><div class="col-md-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked($i?->is_active)><label class="form-check-label">Интеграция включена</label></div></div>
<div class="col-12"><button class="btn btn-primary">Сохранить настройки</button></div></form></div></div>
<div class="col-xl-5"><div class="admin-card p-4 h-100"><h3>Выгрузка</h3><form method="post" action="{{ route('admin.accounting.push') }}" class="row g-2 mb-3">@csrf<div class="col-6"><label class="form-label">С</label><input type="date" class="form-control" name="from" value="{{ now()->startOfMonth()->toDateString() }}" required></div><div class="col-6"><label class="form-label">По</label><input type="date" class="form-control" name="to" value="{{ today()->toDateString() }}" required></div><div class="col-12"><button class="btn btn-success w-100"><i class="bi bi-cloud-arrow-up"></i> Передать в 1С сейчас</button></div></form><hr><form method="post" action="{{ route('admin.accounting.export') }}" class="row g-2">@csrf<div class="col-5"><input type="date" class="form-control" name="from" value="{{ now()->startOfMonth()->toDateString() }}" required></div><div class="col-5"><input type="date" class="form-control" name="to" value="{{ today()->toDateString() }}" required></div><div class="col-2"><select class="form-select" name="format"><option value="json">JSON</option><option value="xml">XML</option></select></div><div class="col-12"><button class="btn btn-outline-primary w-100"><i class="bi bi-download"></i> Скачать файл обмена</button></div></form>@if($i?->last_synced_at)<div class="alert alert-light mt-3 mb-0">Последний успешный обмен: <strong>{{ $i->last_synced_at->format('d.m.Y H:i') }}</strong></div>@endif</div></div>
</div>
<div class="admin-card p-4"><h3>Журнал обмена</h3><div class="table-responsive"><table class="table mini-table align-middle"><thead><tr><th>Время</th><th>Период</th><th>Формат</th><th>Статус</th><th>HTTP</th><th>Записи</th><th>Ошибка</th></tr></thead><tbody>@forelse($runs as $run)<tr><td>{{ $run->started_at?->format('d.m.Y H:i') }}</td><td>{{ $run->period_from?->format('d.m.Y') }} — {{ $run->period_to?->format('d.m.Y') }}</td><td>{{ strtoupper($run->format) }}</td><td><span class="badge {{ $run->status==='completed'?'text-bg-success':($run->status==='failed'?'text-bg-danger':'text-bg-warning') }}">{{ $run->status }}</span></td><td>{{ $run->http_status }}</td><td><small>{{ collect($run->record_counts??[])->map(fn($v,$k)=>$k.': '.$v)->implode(' · ') }}</small></td><td><small class="text-danger">{{ Str::limit($run->error_text,120) }}</small></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Обменов ещё не было.</td></tr>@endforelse</tbody></table></div></div>
@endsection
